import { APP_ROLES, RoleValue } from "../roles";
import { Permission, PERMISSIONS } from "./permissions";

// roles/roleDefinitions.ts
export const ROLE_PERMISSIONS: Record<RoleValue, readonly Permission[]> = {
  [APP_ROLES.CONTROL_PERSONAL]: [
    PERMISSIONS.ASISTENCIA_PERMISO.VIEW,
    PERMISSIONS.ASISTENCIA_PERMISO.CREATE,
    PERMISSIONS.ASISTENCIA_PERMISO.EDIT,
    PERMISSIONS.ASISTENCIA_PERMISO.DELETE,
    PERMISSIONS.DECLARATORIA_COMISION.VIEW,
    PERMISSIONS.DECLARATORIA_COMISION.CREATE,
    PERMISSIONS.DECLARATORIA_COMISION.EDIT,
    PERMISSIONS.TIPO_PERMISO.VIEW,
    PERMISSIONS.TIPO_PERMISO.MANAGE,
    PERMISSIONS.FERIADO_ASUETO.VIEW,
    PERMISSIONS.FERIADO_ASUETO.MANAGE,
    PERMISSIONS.COMISION.VIEW,
    PERMISSIONS.COMISION.CREATE,
    PERMISSIONS.COMISION.EDIT,
    PERMISSIONS.COMISION.DELETE,
  ],
  
  [APP_ROLES.SECRETARIA_RRHH]: [
    PERMISSIONS.DECLARATORIA_COMISION.VIEW,
    PERMISSIONS.DECLARATORIA_COMISION.CREATE,
    PERMISSIONS.DECLARATORIA_COMISION.EDIT,
  ],
  
  [APP_ROLES.ADMINISTRATIVO]: [
    PERMISSIONS.ASISTENCIA_PERMISO.VIEW,
    PERMISSIONS.ASISTENCIA_PERMISO.CREATE,
    PERMISSIONS.COMISION.VIEW,
    PERMISSIONS.COMISION.CREATE,
  ],
  
  [APP_ROLES.ADMINISTRADOR]: [
    ...Object.values(PERMISSIONS).flatMap(module => Object.values(module))
  ],
  
  [APP_ROLES.USUARIO]: [],
  [APP_ROLES.PERSONAL_UPEA]: [],
}